version: '3.7'

services:

  neo4j:
    build:
      context: ./RoutingKit
      dockerfile: Dockerfile
    ports:
      - 7474:7474
      - 7687:7687

  routing-engine:
    build:
      context: ./RoutingKit
      dockerfile: routing-engine/Dockerfile
    ports:
      - 1099:1099
      - 1098:1098
    environment:
      - AGADE_NEO4J_ADDR=bolt://neo4j:7687
      - AGADE_RE_RMI_ADDR_SERVER=routing-engine
    entrypoint: ["/bin/bash", "/usr/src/app/routing-engine/docker-entrypoint.sh"]
    restart: on-failure
    depends_on:
      - neo4j

  agade-backend:
    build:
      context: ./AGADE
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    environment:
      - AGADE_RE_RMI_ADDR_CLIENT=routing-engine



