
package wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AGADETrafficServiceFacadeService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:9000/agadeTraffic?wsdl")
public class AGADETrafficServiceFacadeService
    extends Service
{

    private final static URL AGADETRAFFICSERVICEFACADESERVICE_WSDL_LOCATION;
    private final static WebServiceException AGADETRAFFICSERVICEFACADESERVICE_EXCEPTION;
    private final static QName AGADETRAFFICSERVICEFACADESERVICE_QNAME = new QName("http://service/", "AGADETrafficServiceFacadeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/agadeTraffic?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGADETRAFFICSERVICEFACADESERVICE_WSDL_LOCATION = url;
        AGADETRAFFICSERVICEFACADESERVICE_EXCEPTION = e;
    }

    public AGADETrafficServiceFacadeService() {
        super(__getWsdlLocation(), AGADETRAFFICSERVICEFACADESERVICE_QNAME);
    }

    public AGADETrafficServiceFacadeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGADETRAFFICSERVICEFACADESERVICE_QNAME, features);
    }

    public AGADETrafficServiceFacadeService(URL wsdlLocation) {
        super(wsdlLocation, AGADETRAFFICSERVICEFACADESERVICE_QNAME);
    }

    public AGADETrafficServiceFacadeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGADETRAFFICSERVICEFACADESERVICE_QNAME, features);
    }

    public AGADETrafficServiceFacadeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AGADETrafficServiceFacadeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AGADETrafficServiceFacade
     */
    @WebEndpoint(name = "AGADETrafficServiceFacadePort")
    public AGADETrafficServiceFacade getAGADETrafficServiceFacadePort() {
        return super.getPort(new QName("http://service/", "AGADETrafficServiceFacadePort"), AGADETrafficServiceFacade.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AGADETrafficServiceFacade
     */
    @WebEndpoint(name = "AGADETrafficServiceFacadePort")
    public AGADETrafficServiceFacade getAGADETrafficServiceFacadePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "AGADETrafficServiceFacadePort"), AGADETrafficServiceFacade.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGADETRAFFICSERVICEFACADESERVICE_EXCEPTION!= null) {
            throw AGADETRAFFICSERVICEFACADESERVICE_EXCEPTION;
        }
        return AGADETRAFFICSERVICEFACADESERVICE_WSDL_LOCATION;
    }

}
